ASMSolution/ViewModels/subasset_registrationViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using ASM_UI;

namespace ASM_UI.Models
{
    public class subasset_registrationViewModel
    {
        public subasset_registrationViewModel()
        {

            asset_type_id = (int)Enum_asset_type_Key.AssetChild;  // menandakan sub asset
            asset_parent_list = new List<tr_asset_registration>();
            company_list = new List<ms_asmin_company>();
            asset_reg_location_list = new List<ms_asset_register_location>();
            asset_reg_pic_list = new List<ms_asset_register_pic>();
            asset_category_list = new List<ms_asset_category>();
            vendor_list = new List<ms_vendor>();
            asset_location_list = new List<ms_asset_location>();
            department_list = new List<ms_department>();
            employee_list = new List<ms_employee>();

            tr_asset_images = new tr_asset_image()
            {
                asset_id = 0,
                asset_img_address = base_image_path
            };
        }

        [Key]
        [Display(Name = "Asset ID")]
        public int asset_id { get; set; }

        /// <summary>
        /// 1 : parent
        /// 2 : sub asset (child)
        /// </summary>
        [Display(Name = "Asset Type")]
        public int? asset_type_id { get; set; }
        public virtual ms_asset_type asset_type { get; set; }


        [Display(Name = "Asset Parent Number")]
        public int asset_parent_id { get; set; }
        [Display(Name = "Asset Parent Name")]
        public string asset_parent_name { get; set; }
        public virtual tr_asset_registration asset_parent { get; set; }
        public List<tr_asset_registration> asset_parent_list { get; set; }

        [Display(Name = "Asset Parent Number")]
        public string asset_parent_number { get; set; }

        [StringLength(30)]
        [Display(Name = "Sub-asset Number")]
        public string asset_number { get; set; }


        [Display(Name = "Company")]
        public int? company_id { get; set; }

        public virtual ms_asmin_company company { get; set; }

        public List<ms_asmin_company> company_list { get; set; }


        [Display(Name = "Register Location")]
        public int? asset_reg_location_id { get; set; }

        public virtual ms_asset_register_location asset_reg_location { get; set; }

        public List<ms_asset_register_location> asset_reg_location_list { get; set; }


        [Display(Name = "Register PIC")]
        public int? asset_reg_pic_id { get; set; }

        public virtual ms_asset_register_pic asset_reg_pic { get; set; }

        public List<ms_asset_register_pic> asset_reg_pic_list { get; set; }


        [Display(Name = "Category")]
        public int? category_id { get; set; }

        public virtual ms_asset_category asset_category { get; set; }

        public List<ms_asset_category> asset_category_list { get; set; }


        [StringLength(50)]
        [Display(Name = "Purchase Order No")]
        public string asset_po_number { get; set; }

        [StringLength(50)]
        [Display(Name = "Delivery Order No")]
        public string asset_do_number { get; set; }

        [StringLength(100)]
        [Display(Name = "Sub-asset Name")]
        public string asset_name { get; set; }

        [StringLength(100)]
        [Display(Name = "Sub-asset Brand")]
        public string asset_merk { get; set; }

        [StringLength(50)]
        [Display(Name = "Sub-asset Serial")]
        public string asset_serial_number { get; set; }


        [Display(Name = "Vendor")]
        [Required(ErrorMessage = "Vendor is mandatory")]
        public int? vendor_id { get; set; }

        public virtual ms_vendor vendor { get; set; }

        public List<ms_vendor> vendor_list { get; set; }


        [DataType(DataType.Date)]
        [Display(Name = "Receipt Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? asset_receipt_date { get; set; }

        [Display(Name = "Sub-asset Location")]
        public int? location_id { get; set; }

        public int? current_location_id { get; set; }

        public virtual ms_asset_location asset_location { get; set; }

        public List<ms_asset_location> asset_location_list { get; set; }


        [Display(Name = "Department")]
        public int? department_id { get; set; }

        public int? current_department_id { get; set; }

        public virtual ms_department department { get; set; }

        public List<ms_department> department_list { get; set; }


        [Display(Name = "Employee")]
        public int? employee_id { get; set; }

        public int? current_employee_id { get; set; }

        public virtual ms_employee employee { get; set; }

        public List<ms_employee> employee_list { get; set; }


        [StringLength(200)]
        [Display(Name = "Sub-asset Description")]
        public string asset_description { get; set; }


        public string base_image_path { get; set; }

        [Display(Name = "Upload File")]
        [StringLength(200)]
        public string asset_img_file { get; set; }

        ////[Required]
        //[Display(Name = "Upload File")]
        //public HttpPostedFileBase asset_file_attach { get; set; }

        public virtual tr_asset_image tr_asset_images { get; set; }

        public bool hasImage { get; set; }

        public EnumFormModeKey FormMode { get; set; }

        //QRCode
        [Display(Name = "QRCode Text")]
        public string QRCodeText { get; set; }
        [Display(Name = "QRCode Image")]
        public string QRCodeImagePath { get; set; }

        public static string path_file_qrcode
        {
            get
            {
                return "~/Images/QRCode/";
            }
        }
        public static string path_file_asset
        {
            get
            {
                return "~/Content/AssetImage/";
            }
        }
    }

}

ASMSolution/Controllers/subasset_registrationController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASM_UI.Models;
using ZXing;
using System.Drawing;
using System.Drawing.Imaging;
using ASM_UI.App_Helpers;

namespace ASM_UI.Controllers
{
    [Authorize]
    public class subasset_registrationController : BaseController
    {
        private ModelAsmRemote db = new ModelAsmRemote();
        private string app_root_path;
        private string base_image_path;

        // GET: asubsset_registration
        public ActionResult Index()
        {
            //var _list = db.tr_asset_registration.Where(a => a.fl_active == true && a.deleted_date == null).ToList();
            var _qry = (from ar in db.tr_asset_registration
                        where (ar.fl_active == true && ar.deleted_date == null
                        && ar.company_id == UserProfile.company_id
                        && ar.current_location_id == UserProfile.location_id
                        && ar.asset_type_id == (int)Enum_asset_type_Key.AssetChild)

                        join p in db.tr_asset_registration on ar.asset_parent_id equals p.asset_id
                        where (p.fl_active == true && p.deleted_date == null)
                        //into tmp_t1

                        //from t1 in tmp_t1.
                        join a in db.ms_vendor on ar.vendor_id equals a.vendor_id
                        where (a.fl_active == true && a.deleted_date == null)

                        join b in db.ms_asset_register_location on ar.asset_reg_location_id equals b.asset_reg_location_id
                        where (b.fl_active == true && b.deleted_date == null)

                        join c in db.ms_asset_register_pic on ar.asset_reg_pic_id equals c.asset_reg_pic_id
                        where (c.fl_active == true && c.deleted_date == null)

                        join d in db.ms_asset_type on ar.asset_type_id equals d.activa_type_id
                        where (d.fl_active == true && d.deleted_date == null)

                        join e in db.ms_asset_category on ar.category_id equals e.category_id
                        where (e.fl_active == true && e.deleted_date == null)

                        join f in db.ms_asmin_company on ar.company_id equals f.company_id
                        where (f.fl_active == true && f.deleted_date == null)

                        join g in db.ms_department on ar.department_id equals g.department_id
                        where (g.fl_active == true && g.deleted_date == null)

                        join h in db.ms_employee on ar.employee_id equals h.employee_id
                        where (h.fl_active == true && h.deleted_date == null)

                        join i in db.ms_asset_location on ar.location_id equals i.location_id
                        where (i.fl_active == true && i.deleted_date == null)

                        select new subasset_registrationViewModel()
                        {
                            asset_parent = p,
                            asset_parent_id = (int)ar.asset_parent_id,
                            asset_id = ar.asset_id,
                            asset_type_id = ar.asset_type_id,
                            asset_type = d,
                            asset_number = ar.asset_number,
                            company_id = ar.company_id,
                            company = f,
                            asset_reg_location_id = ar.asset_reg_location_id,
                            asset_reg_location = b,
                            asset_reg_pic_id = ar.asset_reg_pic_id,
                            asset_reg_pic = c,
                            category_id = ar.category_id,
                            asset_category = e,
                            asset_po_number = ar.asset_po_number,
                            asset_do_number = ar.asset_do_number,
                            asset_name = ar.asset_name,
                            asset_merk = ar.asset_merk,
                            asset_serial_number = ar.asset_serial_number,
                            vendor_id = ar.vendor_id,
                            vendor = a,
                            asset_receipt_date = ar.asset_receipt_date,
                            location_id = ar.location_id,
                            asset_location = i,
                            department_id = ar.department_id,
                            department = g,
                            employee_id = ar.employee_id,
                            employee = h,
                            asset_description = ar.asset_description
                        }).ToList<subasset_registrationViewModel>();

            return View(_qry);
        }

        [HttpGet]
        public JsonResult List()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var query_result = (from ar in db.tr_asset_registration
                                where (ar.fl_active == true && ar.deleted_date == null
                                && ar.company_id == UserProfile.company_id
                                && ar.current_location_id == UserProfile.location_id
                                && ar.asset_type_id == (int)Enum_asset_type_Key.AssetChild)

                                join p in db.tr_asset_registration on ar.asset_parent_id equals p.asset_id
                                where (p.fl_active == true && p.deleted_date == null)

                                join a in db.ms_vendor on ar.vendor_id equals a.vendor_id
                                where (a.fl_active == true && a.deleted_date == null)

                                join b in db.ms_asset_register_location on ar.asset_reg_location_id equals b.asset_reg_location_id
                                where (b.fl_active == true && b.deleted_date == null)

                                join c in db.ms_asset_register_pic on ar.asset_reg_pic_id equals c.asset_reg_pic_id
                                where (c.fl_active == true && c.deleted_date == null)

                                join d in db.ms_asset_type on ar.asset_type_id equals d.activa_type_id
                                where (d.fl_active == true && d.deleted_date == null)

                                join e in db.ms_asset_category on ar.category_id equals e.category_id
                                where (e.fl_active == true && e.deleted_date == null)

                                join f in db.ms_asmin_company on ar.company_id equals f.company_id
                                where (f.fl_active == true && f.deleted_date == null)

                                join g in db.ms_department on ar.department_id equals g.department_id
                                where (g.fl_active == true && g.deleted_date == null)

                                join h in db.ms_employee on ar.employee_id equals h.employee_id
                                where (h.fl_active == true && h.deleted_date == null)

                                join i in db.ms_asset_location on ar.location_id equals i.location_id
                                where (i.fl_active == true && i.deleted_date == null)

                                select new subasset_registrationViewModel()
                                {
                                    asset_parent_id = (int)ar.asset_parent_id,
                                    asset_parent_number = p.asset_number,
                                    asset_parent_name = p.asset_name,
                                    asset_id = ar.asset_id,
                                    asset_type_id = ar.asset_type_id,
                                    asset_type = d,
                                    asset_number = ar.asset_number,
                                    company_id = ar.company_id,
                                    company = f,
                                    asset_reg_location_id = ar.asset_reg_location_id,
                                    asset_reg_location = b,
                                    asset_reg_pic_id = ar.asset_reg_pic_id,
                                    asset_reg_pic = c,
                                    category_id = ar.category_id,
                                    asset_category = e,
                                    asset_po_number = ar.asset_po_number,
                                    asset_do_number = ar.asset_do_number,
                                    asset_name = ar.asset_name,
                                    asset_merk = ar.asset_merk,
                                    asset_serial_number = ar.asset_serial_number,
                                    vendor_id = ar.vendor_id,
                                    vendor = a,
                                    asset_receipt_date = ar.asset_receipt_date,
                                    location_id = ar.location_id,
                                    asset_location = i,
                                    department_id = ar.department_id,
                                    department = g,
                                    employee_id = ar.employee_id,
                                    employee = h,
                                    asset_description = ar.asset_description
                                }).ToList();

            return Json(new { data = query_result }, JsonRequestBehavior.AllowGet);
        }


        // GET: asset_registration/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tr_asset_registration tr_asset_registration = db.tr_asset_registration.Find(id);
            if (tr_asset_registration == null)
            {
                return HttpNotFound();
            }

            var _qry = (from ar in db.tr_asset_registration

ASMSolution/Views/subasset_registration/Index.cshtml
@model IEnumerable<ASM_UI.Models.subasset_registrationViewModel>
@{
    ViewBag.Title = "Sub-asset Registration";
}

<div id="content">
    <!-- row -->
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                Registration
                <span>
                    >
                    Sub Asset Registration
                </span>
            </h1>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            <!-- Button trigger modal -->
            <a class="btn btn-primary btn-lg pull-right header-btn hidden-mobile" href="@Url.Action("Create", "subasset_registration", new { id = 0 }, Request.Url.Scheme)"><i class='fa fa-plus'></i>Sub Asset</a>
        </div>

    </div>

    <section id="widget-grid" class="">

        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Sub Asset Registration List</h2>

                    </header>
                    <div>
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <div class="widget-body no-padding">
                            <table class="table table-striped table-bordered table-hover" width="100%" id="table_basic">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.company_id)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.category_id)
                                        </th>
                                        <th>
                                            Sub Asset Number
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_merk)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_receipt_date)
                                        </th>
                                        <th>
                                            Parent Number
                                        </th>
                                        <th>Parent Name</th>
                                        <th colspan="2" width="5%">Action</th>
                                        <th hidden="hidden" width="5%"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </article>
        </div>

    </section>
</div>


@section pagespecific {
    <script type="text/javascript">
        function DeleteData(id) {
            swal({
                title: "Are you sure want to Delete this data?",
                text: "(this process can\'t be undo)",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Sure!",
                closeOnConfirm: false,
                closeOnEsc: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                preConfirm: () => {
                    return new Promise(() => {
                        //ajax side
                        swal({
                            title: 'Please wait... delete data in progress....',
                            onOpen: function () {
                                swal.showLoading()
                                $.ajax({
                                    type: "GET",
                                    url: "/subasset_registration/Delete/" + id,
                                    success: function (data) {
                                        if (data == "1") {
                                            swal.close();
                                            swal("Success", "Success Delete Data", "success");
                                            setTimeout(location.reload(true), 5000);
                                            //window.location.href = "/asset_registration/index";
                                        }
                                        else {
                                            swal("Failed", "Failed Delete Data", "error");
                                        }

                                    },
                                });
                            }
                        });
                    })
                },
                allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
                if (result.dismiss) {
                    swal("Cancel", "You Cancel Delete Data", "error");
                }
            });
        }
        $(document).ready(function () {
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            $('#table_basic').dataTable({
                "ajax": {
                    "url": "/subasset_registration/List/",
                    "type": "GET",
                    "datatype": "json",
                },
                    "columns": [
                            { "data": "company.company_code", "autoWidth": true },
                            { "data": "asset_category.category_name", "autoWidth": true },
                            { "data": "asset_number", "autoWidth": true },
                            { "data": "asset_name", "autoWidth": true },
                            { "data": "asset_merk", "autoWidth": true },
                            {
                                "data": "asset_receipt_date", "autoWidth": true, type: 'date',
                                render: function (data, type, row) { return data ? moment(data).format('DD-M-YYYY') : ''; }
                            },
                            { "data": "asset_parent_name", "autoWidth": true },
                            { "data": "asset_parent_number", "autoWidth": true },
                            {
                                "data": "action",
                                "autowidth": true,
                                "mRender": function (data, type, full) {
                                    return '<a href="/subasset_registration/edit/' + full['asset_id'] + '">' + 'Edit' + '</a>';
                                }
                            },
                            {
                                "data": "action",
                                "autowidth": true,
                                "mRender": function (data, type, full) {
                                    return '<a href="/subasset_registration/Details/' + full['asset_id'] + '">' + 'Detail' + '</a>';
                                }
                            }
                            //{
                            //    "data": "action",
                            //    "autowidth": true,
                            //    "mRender": function (data, type, full) {
                            //        return '<a href="#" onclick="DeleteData(' + full['asset_id'] + ')">' + 'Delete' + '</a>';
                            //    }
                            //}

                    ]
                },
                {
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#table_basic'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });
        });

    </script>
}

ASMSolution/Views/subasset_registration/ModalAsset.cshtml
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                &times;
            </button>
            <h4 class="modal-title">
                Asset List
            </h4>
        </div>
        <div class="modal-body no-padding">
            <div>
                @*<table id="jqgridAsset" style="width:400px"></table>
                    <div id="pjqgridAsset"></div>*@

                <table id="AssetTblList" class="table table-bordered table-hover table-striped" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Asset ID</th>
                            <th>Asset Number</th>
                            <th>Asset Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>



            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
                Cancel
            </button>

        </div>
    </div><!-- /.modal-content -->

</div><!-- /.modal-dialog -->