ASMSolution/ViewModels/user_accountViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web.Mvc;
using ASM_UI;

namespace ASM_UI.Models
{
    public class user_accountViewModel
    {
        [Key]
        public int user_id { get; set; }

        [StringLength(50)]
        [Required]
        [Display(Name = "User Name")]
        public string user_name { get; set; }

        [StringLength(100)]
        [Display(Name = "User Password")]
        public string user_password { get; set; }

        [Display(Name = "User Type")]
        public int user_type_id { get; set; }

        public string user_type_name { get; set; }
        public IEnumerable<SelectListItem> sli_user_type_list { get; set; }

        [Display(Name = "Employee")]
        public int employee_id { get; set; }

        [StringLength(20)]
        [Display(Name = "NIK")]
        public string employee_nik { get; set; }

        [StringLength(50)]
        [Display(Name = "Employee Name")]
        public string employee_name { get; set; }

        [StringLength(50)]
        [Display(Name = "Email Address")]
        public string employee_email { get; set; }

        [Display(Name = "Active")]
        public string rec_isactive { get; set; }

        [Display(Name = "Flag Active")]
        public bool? fl_active { get; set; }

        [Display(Name = "Last Modified Date")]
        public DateTime? rec_modified_date { get; set; }

        [Display(Name = "Last Modified By")]
        public string rec_modified_by { get; set; }

        public EnumFormModeKey FormMode { get; set; }

    }

}

ASMSolution/Controllers/user_accountController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASM_UI.Models;

namespace ASM_UI.Controllers
{
    [Authorize]
    public class user_accountController : BaseController
    {
        private ModelAsmRemote db = new ModelAsmRemote();

        // GET: user
        public ActionResult Index()
        {
            //var _list = (from t1 in db.ms_user
            //             where (t1.deleted_date == null)
            //             join t2 in db.ms_employee on t1.employee_id equals t2.employee_id
            //             join u in db.ms_user on t1.updated_by equals u.user_id
            //             into t_joined
            //             from row_join in t_joined.DefaultIfEmpty()
            //             from usr in db.ms_user.Where(rec => (rec == null) ? false : rec.user_id == row_join.user_id).DefaultIfEmpty()
            //             select new
            //             {
            //                 user_id = t1.user_id,
            //                 user_name = t1.user_name,
            //                 employee_id = t2.employee_id,
            //                 employee_nik = t2.employee_nik,
            //                 employee_name = t2.employee_name,
            //                 employee_email = t2.employee_email,
            //                 rec_isactive = (t1.fl_active == true) ? "Yes" : "No",
            //                 //rec_isactive_2 = Enum.GetName(typeof(EnumBooleanKey), t1.fl_active),
            //                 rec_modified_by = (usr == null) ? string.Empty : usr.user_name,
            //                 rec_modified_date = t1.updated_date
            //             }).ToList()
            //             .Select(c => new user_accountViewModel()
            //             {
            //                 user_id = c.user_id,
            //                 user_name = c.user_name,
            //                 employee_id = c.employee_id,
            //                 employee_nik = c.employee_nik,
            //                 employee_name = c.employee_name,
            //                 employee_email = c.employee_email,
            //                 rec_isactive = c.rec_isactive,
            //                 rec_modified_by = c.rec_modified_by,
            //                 rec_modified_date = c.rec_modified_date
            //             });

            //return View(_list);
            return View();
        }

        public JsonResult List(string sidx, string sord, int page, int rows, bool _search, string searchField, string searchOper, string searchString)
        {
            sord = (sord == null) ? "" : sord;
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var _list = (from u1 in db.ms_user
                         join u3 in db.ms_user_type on u1.user_type_id equals u3.user_type_id
                         where (u1.deleted_date == null)
                         join e in db.ms_employee on u1.employee_id equals e.employee_id
                         join u2 in db.ms_user on u1.updated_by equals u2.user_id
                         into t_joined
                         from row_join in t_joined.DefaultIfEmpty()
                         from usr in db.ms_user.Where(rec_udated_by => (rec_udated_by == null) ? false : rec_udated_by.user_id == row_join.user_id).DefaultIfEmpty()

                         select new
                         {
                             user_id = u1.user_id,
                             user_name = u1.user_name,
                             user_password = u1.user_password,
                             user_type_id = u1.user_type_id,
                             user_type_name = u3.user_type_name,

                             employee_id = e.employee_id,
                             employee_nik = e.employee_nik,
                             employee_name = e.employee_name,
                             employee_email = e.employee_email,
                             rec_isactive = (u1.fl_active == true) ? "Yes" : "No",
                             //rec_isactive_2 = Enum.GetName(typeof(EnumBooleanKey), u1.fl_active),
                             rec_modified_by = (usr == null) ? string.Empty : usr.user_name,
                             rec_modified_date = u1.updated_date
                         }).ToList()
                        .Select(c => new user_accountViewModel()
                        {
                            user_id = c.user_id,
                            user_name = c.user_name,
                            user_password = c.user_password,
                            user_type_id = c.user_type_id,
                            user_type_name = c.user_type_name,
                            employee_id = c.employee_id,
                            employee_nik = c.employee_nik,
                            employee_name = c.employee_name,
                            employee_email = c.employee_email,
                            rec_isactive = c.rec_isactive,
                            rec_modified_by = c.rec_modified_by,
                            rec_modified_date = c.rec_modified_date
                        });

            // search function
            if (_search)
            {
                switch (searchField)
                {
                    case "user_name":
                        _list = _list.Where(t => t.user_name.Contains(searchString));
                        break;
                    case "employee_nik":
                        _list = _list.Where(t => t.employee_nik.Contains(searchString));
                        break;
                    case "employee_name":
                        _list = _list.Where(t => t.employee_name.Contains(searchString));
                        break;
                    case "employee_email":
                        _list = _list.Where(t => t.employee_email.Contains(searchString));
                        break;
                }
            }
            //calc paging
            int totalRecords = _list.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            //default sorting
            if (sord.ToUpper() == "DESC")
            {
                _list = _list.OrderByDescending(t => t.user_name);
                _list = _list.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                _list = _list.OrderBy(t => t.user_name);
                _list = _list.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = _list
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        ////GET: user/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ms_user ms_user = db.ms_user.Find(id);
        //    if (ms_user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ms_user);
        //}

        public ActionResult ModalFrm(int? id = 0)
        {
            user_accountViewModel usr_acc = null;
            int user_id = (int)id;
            ms_user ms_user = db.ms_user.Find(user_id);
            if (ms_user == null)
            {
                usr_acc = new user_accountViewModel()
                {
                    fl_active = true,
                    rec_isactive = "Yes",
                    user_id = 0,
                    user_type_id = 0,
                    employee_id = 0
                };
            }
            else
            {
                usr_acc = new user_accountViewModel()
                {
                    fl_active = true,
                    rec_isactive = "Yes",
                    user_id = ms_user.user_id,
                    user_name = ms_user.user_name,
                    user_password =  App_Helpers.CryptorHelper.Decrypt(ms_user.user_password, "MD5", true),
                    user_type_id = ms_user.user_type_id,
                    user_type_name = ms_user.ms_user_type.user_type_name,

                    employee_id = ms_user.ms_employee.employee_id,
                    employee_nik = ms_user.ms_employee.employee_nik,
                    employee_name = ms_user.ms_employee.employee_name,
                    employee_email = ms_user.ms_employee.employee_email
                };

            }

            List<SelectListItem> first = new List<SelectListItem> { new SelectListItem { Text = "- [Not Set] -", Value = "0", Selected = true } };
            usr_acc.sli_user_type_list = (from t in db.ms_user_type
                                          where (t.fl_active == true && t.deleted_date == null)
                                          select new SelectListItem
                                          {
                                              Text = t.user_type_name,
                                              Value = t.user_type_id.ToString()
                                          }
                          ).ToList<SelectListItem>().Union(first);

            usr_acc.FormMode = (user_id > 0) ? EnumFormModeKey.Form_Edit : EnumFormModeKey.Form_New;
            return PartialView(usr_acc);
        }


        public ActionResult EmployeeModal()
        {
            return PartialView();
        }

        /// <summary>
        /// data untuk employee modal, 
        /// 
        /// tampilkan hanya yang belum memiliki use id. user id yang di nonaktifkan, 
        /// masi bisa dipakai tinggal akifkan lagi aja
        /// </summary>
        /// <param name="id"></param>

ASMSolution/Views/user_account/Create.cshtml
@model ASM_UI.Models.user_accountViewModel
@{
    ViewBag.Title = "New User Account";
}
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                User Management
                <span>
                    >
                    User Account Form
                </span>
            </h1>
        </div>
    </div>

    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false" data-widget-togglebutton="false" data-widget-collapsed="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                        <h2>User Account</h2>

                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            @using (Html.BeginForm("Create", "user_account", FormMethod.Post, htmlAttributes: new { @class = "smart-form" }))
                            {
                                <header>
                                    New User Account Form
                                </header>

                                <fieldset>

                                    <fieldset>
                                        @Html.AntiForgeryToken()
                                        <br />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.user_id)
                                        @Html.HiddenFor(model => model.employee_id)
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.employee_nik, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-5">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_nik, new { htmlAttributes = new { @class = "form-control", placeholder = "Employee NIK" } })
                                                        @Html.ValidationMessageFor(model => model.employee_nik, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>

                                                <div class="col-lg-1">
                                                    <a data-toggle="modal" href="#Employee" class="btn btn-success btn-sm" onclick="OpenModalEmployeeList();"><i class="fa fa-search fa-lg"></i></a>
                                                </div>

                                            </div>
                                        </section>

                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.employee_name, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_name, new { htmlAttributes = new { @class = "form-control", @readonly = "true", placeholder = "Employee Name" } })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>

                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.employee_email, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_email, new { htmlAttributes = new { @class = "form-control", @readonly = "true", placeholder = "Employee Email Address" } })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>

                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.user_name, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control", placeholder = "User Login" } })
                                                        @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>

                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.user_password, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.user_password, new { htmlAttributes = new { @class = "form-control", placeholder = "User Password" } })
                                                        @Html.ValidationMessageFor(model => model.user_password, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>

                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.fl_active, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-md-8">
                                                        <label class="checkbox">
                                                            @{var str_checked = "";
                                                                if (Model.fl_active == true)
                                                                {
                                                                    str_checked = "checked=\"checked\"";
                                                                }
                                                            }
                                                            <input type="checkbox" @str_checked name="fl_active" id="fl_active" />
                                                            <i></i>Yes

                                                        </label>
                                                </div>
                                            </div>
                                        </section>

                                    </fieldset>

                                </fieldset>

                                <footer>
                                    <div class="form-group">
                                        <div class="col-md-7">
                                            @Html.ActionLink("Cancel", "Index", "user_account", htmlAttributes: new { @class = "btn btn-default" })
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </footer>
                            }
                        </div>
                    </div>
                </div>
            </article>

        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="Employee" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
    </div>
</div>

@section pagespecific {
    <script type="text/javascript">
        $(document).ready(function () {

            //$('#a_date').datepicker({
            //    dateFormat: 'dd-mm-yy',
            //    prevText: '<i class="fa fa-chevron-left"></i>',
            //    nextText: '<i class="fa fa-chevron-right"></i>',
            //});

        });

        function GetEmployee(id) {
            $('#CancelBtn').prop('disabled', true);

            $.ajax({
                type: 'POST',
                url: "/user_account/GetEmployeeList/" + id,
                dataType: 'json',
                success: function (data) {
                    for (var i in data) {
                        $("#employee_id").val(data[i].employee_id);
                        $("#employee_nik").val(data[i].employee_nik);
                        $("#employee_name").val(data[i].employee_name);
                        $("#employee_email").val(data[i].employee_email);
                    }
                },
                error: function (data) {
                    alert("error!");
                }
            })
        }


        function OpenModalEmployeeList() {
            $("#Employee").html("");
            var empployee_id = $("#employee_id").val();
            //alert("modal \n" + empployee_id);

            $.ajax({
                url: "/user_account/EmployeeModal/",
                success: function (data) {
                    $("#Employee").html(data);
                    //alert("open modal");
                    var oTable = $('#EmployeeTblList').DataTable({
                        "ajax": {
                            "url": "/user_account/GetEmployeeList/0",
                            "type": "GET",
                            "datatype": "json",
                        },
                        "columns": [
                            { "data": "employee_id", "autoWidth": true },
                            { "data": "employee_nik", "autoWidth": true },
                            { "data": "employee_name", "autoWidth": true },
                            { "data": "employee_email", "autoWidth": true },
                            {
                                "data": "action",
                                "autowidth": true,
                                "mRender": function (data, type, full) {
                                    return '<a class="btn btn-xs btn-primary" data-dismiss="modal" onclick="GetEmployee(' + full['employee_id'] + ');">' + 'Select' + '</a>';
                                }
                            }
                        ]
                    });
                }
            });
        }

    </script>
}

ASMSolution/Views/user_account/EmployeeModal.cshtml
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                &times;
            </button>
            <h4 class="modal-title">
                Employee List
            </h4>
        </div>

        <div class="modal-body no-padding">
            <div>
                <table id="EmployeeTblList" class="table table-bordered table-hover table-striped" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NIK</th>
                            <th>Employee</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>

        <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-7">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

        </div>

    </div><!-- /.modal-content -->

</div><!-- /.modal-dialog -->