ASMSolution/Controllers/asset_searchController.cs
using System;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ASM_UI.Models;
using System.Data.SqlClient;
using System.Web.Configuration;

namespace ASM_UI.Controllers
{
    [Authorize]
    public class asset_searchController : Controller
    {
        private ModelAsmRemote db = new ModelAsmRemote();
      
        // GET: asset_search
        public ActionResult Index(string strAssetNumber, string strAssetName, string strMerk, string TypeSelectLoc, string TypeSelect)
        {
            #region "for dropdown Location"
            var _Location = from s in db.ms_asset_location
                            where (s.fl_active == true && s.deleted_date == null)
                            select s;

            SelectList itemsTypeLoc = new SelectList(_Location, "location_code", "location_name", TypeSelectLoc);

            ViewBag.TypeSelectLoc = itemsTypeLoc;
            ViewBag.TypeSelectValue = TypeSelectLoc;
            #endregion

            #region "for dropdown Category"
            var _Category = from s in db.ms_asset_category
                            where (s.fl_active == true && s.deleted_date == null)
                            select s;

            SelectList itemsType = new SelectList(_Category, "category_code", "category_name", TypeSelect);

            ViewBag.TypeSelect = itemsType;
            ViewBag.TypeSelectValue = TypeSelect;
            #endregion

            return View();
        }

        /// <summary>
        /// list utk license index
        /// </summary>
        /// <returns>JSON</returns>
        public JsonResult GetAssetSearchList(string strAssetNumber, string strAssetName, string strMerk, string TypeSelectLoc, string TypeSelect)
        {
            db.Configuration.ProxyCreationEnabled = false;

            if (String.IsNullOrEmpty(strAssetNumber))
                strAssetNumber = string.Empty;

            if (String.IsNullOrEmpty(strAssetName))
                strAssetName = string.Empty;

            if (String.IsNullOrEmpty(strMerk))
                strMerk = string.Empty;

            if (String.IsNullOrEmpty(TypeSelectLoc) || TypeSelect == "ALL")
                TypeSelectLoc = string.Empty;

            if (String.IsNullOrEmpty(TypeSelect) || TypeSelect == "ALL")
                TypeSelect = string.Empty;

            var _qry = (from ar in db.tr_asset_registration
                        where (ar.fl_active == true && ar.deleted_date == null 
                        //&& ar.asset_type_id == (int)Enum_asset_type_Key.AssetParent
                        && ar.asset_number.Contains(strAssetNumber) 
                        && ar.asset_name.Contains(strAssetName) 
                        && ar.asset_merk.Contains(strMerk))
                        //&& ar.company_id == UserProfile.company_id 
                        //&& ar.department_id == UserProfile.department_id
                        join a in db.ms_vendor on ar.vendor_id equals a.vendor_id
                        where (a.fl_active == true && a.deleted_date == null)

                        join b in db.ms_asset_register_location on ar.asset_reg_location_id equals b.asset_reg_location_id
                        where (b.fl_active == true && b.deleted_date == null)

                        join c in db.ms_asset_register_pic on ar.asset_reg_pic_id equals c.asset_reg_pic_id
                        where (c.fl_active == true && c.deleted_date == null)

                        join d in db.ms_asset_type on ar.asset_type_id equals d.activa_type_id
                        where (d.fl_active == true && d.deleted_date == null)

                        join e in db.ms_asset_category on ar.category_id equals e.category_id
                        where (e.fl_active == true && e.deleted_date == null && e.category_code.Contains(TypeSelect))

                        join f in db.ms_asmin_company on ar.company_id equals f.company_id
                        where (f.fl_active == true && f.deleted_date == null)

                        join g in db.ms_department on ar.department_id equals g.department_id
                        where (g.fl_active == true && g.deleted_date == null)

                        join h in db.ms_employee on ar.employee_id equals h.employee_id
                        where (h.fl_active == true && h.deleted_date == null)

                        join i in db.ms_asset_location on ar.location_id equals i.location_id
                        where (i.fl_active == true && i.deleted_date == null && i.location_code.Contains(TypeSelectLoc))

                        select new asset_registrationViewModel()
                        {
                            asset_id = ar.asset_id,
                            asset_type_id = ar.asset_type_id,
                            asset_type = d,
                            asset_number = ar.asset_number,
                            company_id = ar.company_id,
                            company = f,
                            asset_reg_location_id = ar.asset_reg_location_id,
                            asset_reg_location = b,
                            asset_reg_pic_id = ar.asset_reg_pic_id,
                            asset_reg_pic = c,
                            category_id = ar.category_id,
                            asset_category = e,
                            asset_po_number = ar.asset_po_number,
                            asset_do_number = ar.asset_do_number,
                            asset_name = ar.asset_name,
                            asset_merk = ar.asset_merk,
                            asset_serial_number = ar.asset_serial_number,
                            vendor_id = ar.vendor_id,
                            vendor = a,
                            asset_receipt_date = ar.asset_receipt_date,
                            location_id = ar.location_id,
                            asset_location = i,
                            department_id = ar.department_id,
                            department = g,
                            employee_id = ar.employee_id,
                            employee = h,
                            asset_description = ar.asset_description
                        }).ToList<asset_registrationViewModel>();

            return Json(new { data = _qry }, JsonRequestBehavior.AllowGet);
        }

        // GET: asset_search/Details/11
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string constring = WebConfigurationManager.ConnectionStrings["ModelAsmRemote"].ConnectionString;
            var conn = new SqlConnection(constring);

            var cmd = new SqlCommand("SEARCHASSETBYID", conn);
            cmd.CommandText = "Exec SP_SEARCH_ASSETBYID @asset_id";

            cmd.Parameters.AddWithValue("@asset_id", id);
            conn.Open();
            cmd.ExecuteNonQuery();

            SqlDataAdapter dataAdapt = new SqlDataAdapter();
            dataAdapt.SelectCommand = cmd;
            DataTable dataTable = new DataTable();
            dataAdapt.Fill(dataTable);

            conn.Close();

            asset_registrationViewModel data = new asset_registrationViewModel();
            data.asset_id = Convert.ToInt32(dataTable.Rows[0]["asset_id"]);
            data.asset_number = dataTable.Rows[0]["asset_number"].ToString();
            data.asset_name = dataTable.Rows[0]["asset_name"].ToString();
            data.company_register = dataTable.Rows[0]["company_register"].ToString();
            data.asset_merk = dataTable.Rows[0]["asset_merk"].ToString();
            data.location_register = dataTable.Rows[0]["location_register"].ToString();
            data.asset_serial_number = dataTable.Rows[0]["asset_serial_number"].ToString();
            data.pic_register = dataTable.Rows[0]["pic_register"].ToString();
            data.asset_description = dataTable.Rows[0]["asset_description"].ToString();
            data.category_register = dataTable.Rows[0]["category_register"].ToString();
            data.asset_receipt_date = Convert.ToDateTime(dataTable.Rows[0]["asset_receipt_date"]);
            data.vendor_name = dataTable.Rows[0]["vendor_name"].ToString();
            data.location_asset = dataTable.Rows[0]["location_asset"].ToString();
            data.original_price = isnullnumber(dataTable.Rows[0]["original_price"]);
            data.department_asset = dataTable.Rows[0]["department_asset"].ToString();
            data.usage_life_time_fiskal = dataTable.Rows[0]["usage_life_time_fiskal"].ToString();
            data.employee_name = dataTable.Rows[0]["employee_name"].ToString();
            data.fis_book_value = isnullnumber(dataTable.Rows[0]["fis_book_value"]);
            return View(data);
        }

        private Decimal isnullnumber(object oData)
        {
            if (oData == DBNull.Value)
                return 0;
            else
                return Convert.ToDecimal(oData);
        }
    }
}

ASMSolution/Views/asset_search/Index.cshtml
@model IEnumerable<ASM_UI.Models.asset_registrationViewModel>

@{
    ViewBag.Title = "Asset Search";
}

<div id="content">
    <!-- row -->
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                General
                <span>
                    >
                    Asset Search
                </span>
            </h1>
        </div>
    </div>
    <section id="widget-grid" class="">

        @using (Html.BeginForm("Index", "asset_search", FormMethod.Post))
        {
            <div class="row">
                <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="jarviswidget jarviswidget-color-darken" id="wid-id-filter" data-widget-editbutton="false">

                        <header>
                            <h2>Search Criteria</h2>
                        </header>
                        <div class="row">
                            <div class="row">
                                <div class="col-md-2">
                                    <label class="control-label"><b>Asset Number</b></label>
                                </div>
                                <div class="col-md-5">
                                    @Html.TextBox("strAssetNumber", (string)ViewBag.CurrentFilter, htmlAttributes: new { id = "strAssetNumber", @class = "form-control" })
                                    <label></label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <label class="control-label"><b>Location</b></label>
                                </div>
                                <div class="col-md-3">
                                    <label class="input">
                                        @Html.DropDownList("TypeSelectLoc", null, "ALL", htmlAttributes: new { id = "TypeSelectLoc", @class = "form-control" })
                                    </label>
                                </div>
                                <div class="col-md-1">
                                </div>
                                <div class="col-md-2">
                                    <label class="control-label"><b>Asset Name</b></label>
                                </div>
                                <div class="col-md-3">
                                    <label class="input">
                                        @Html.TextBox("strAssetName", (string)ViewBag.CurrentFilter, htmlAttributes: new { id = "strAssetName", @class = "form-control" })
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <label class="control-label"><b>Category</b></label>
                                </div>
                                <div class="col-md-3">
                                    <label class="input">
                                        @Html.DropDownList("TypeSelect", null, "ALL", htmlAttributes: new { id = "TypeSelect", @class = "form-control" })
                                    </label>
                                </div>
                                <div class="col-md-1">
                                </div>
                                <div class="col-md-2">
                                    <label class="control-label"><b>Merk</b></label>
                                </div>
                                <div class="col-md-3">
                                    <label class="input">
                                        @Html.TextBox("strMerk", (string)ViewBag.CurrentFilter, htmlAttributes: new { id = "strMerk", @class = "form-control" })
                                    </label>
                                </div>
                            </div>
                            <br />
                            <footer>
                                <input type="submit" value="Search" class="btn btn-primary" />
                                <a class="btn btn-default" href="@Url.Action("Index", "asset_search")">Cancel</a>
                            </footer>
                            <br />
                        </div>
                    </div>
                </article>
            </div>
        }
        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Asset List</h2>

                    </header>
                    <div>
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <div class="widget-body no-padding">
                            <table class="table table-striped table-bordered table-hover" width="100%" id="table_basic">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_number)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.asset_merk)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.location_id)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.department_id)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.employee_id)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.category_id)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </article>
        </div>

    </section>
</div>


@section pagespecific {
    <script type="text/javascript">

        $(document).ready(function () {
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            var strAssetNumber = document.getElementById('strAssetNumber').value;
            var strAssetName = document.getElementById('strAssetName').value;
            var strMerk = document.getElementById('strMerk').value;
            var TypeSelectLoc = document.getElementById('TypeSelectLoc').value;
            var TypeSelect = document.getElementById('TypeSelect').value;

            $('#table_basic').dataTable(

                {"ajax": {
                    "url": "/asset_search/GetAssetSearchList?strAssetNumber=" + document.getElementById('strAssetNumber').value +
                                                           "&strAssetName=" + document.getElementById('strAssetName').value +
                                                           "&strMerk=" + document.getElementById('strMerk').value +
                                                           "&TypeSelectLoc=" + document.getElementById('TypeSelectLoc').value +
                                                           "&TypeSelect=" + document.getElementById('TypeSelect').value,
                    "type": "POST",
                    "datatype": "json",
                },
                    "columns": [
                        { "data": "asset_number", "autoWidth": true },
                        { "data": "asset_name", "autoWidth": true },
                        { "data": "asset_merk", "autoWidth": true },
                        { "data": "asset_location.location_name", "autoWidth": true },
                        { "data": "department.department_code", "autoWidth": true },
                        { "data": "employee.employee_name", "autoWidth": true },
                        { "data": "asset_category.category_name", "autoWidth": true },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="/asset_search/Details/' + full['asset_id'] + '?idw=0">' + 'Select' + '</a>';
                            }
                        }
                    ]
                },
            {
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "oLanguage": {
                    "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                },
                "preDrawCallback": function () {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#table_basic'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function (oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });
        });

    </script>
}